### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/DroneDB#140]
Users should be able to add geotagged annotations to a dataset (or a directory, or both).

**Comment by HeDo88TH** [comment]
We could make the ID a UUID, this way we will have a reasonable (https://stackoverflow.com/a/39776) way to merge during push/pull.

I like the idea of using a "category" column to better identify the annotation.

**Comment by pierotofy** [comment]
| UUID (pk) | path (index)  | key (index) | value   | mtime       |
|------|--------------|-----------|------------|------------|
|xxxxx| DJI_0001.jpg | annotations | {JSON} | 1627467648 |
|yyyyy| DJI_0001.jpg | annotations | {JSON} | 1627467648 |
|zzzzz| DJI_0001.jpg | info | {JSON} | 1627467648 |
| ... | ... | ... |... | ...|

 - `ddb meta add annotation [-p DJI_0001.jpg] <json>` --> Adds `annotations` (add `s` suffix)
 - `ddb meta set annotation [-p DJI_0001.jpg] <json>` --> Adds `annotation` (overrides previous `annotation` key if one exists). 
 - `ddb meta set annotations [-p DJI_0001.jpg] <json>` --> Error, annotations is plural.
 - `ddb meta rm <id>` --> Delete entry
 - `ddb meta get annotations [-p DJI_0001.jpg]` --> Print JSON array of annotations
 - `ddb meta get annotation [-p DJI_0001.jpg` --> Print JSON key (which should be unique for the given path)
 - `ddb meta unset annotation [-p DJI_0001.jpg]` --> Remove entry `annotation`
 - `ddb meta unset annotations [-p DJI_0001.jpg]` --> Remove all `annotations` entries for path.

`-p` defaults to `.` if unspecified (the DroneDB database itself).

**Comment by pierotofy** [comment]
Issues like https://github.com/DroneDB/Hub/issues/29 can then be trivially solved by adding client side logic for:

`ddb meta set potree_settings <potree settings>` and `ddb meta get potree_settings`.

**Comment by pierotofy** [comment]
`ddb meta get annotations [-p DJI_0001.jpg]` --> ```
[{ _id: <uuid>, jsonField: jsonValue, ...}, {_id: <uuid>, jsonField: jsonValue, ...}, ...]
```

`ddb meta get potree [-p DJI_0001.jpg]` --> ```
{ _id: <uuid>, jsonField: jsonValue, ... }
```
