### ISSUE TITLE
OneDrive issue

### ISSUE THREAD

**Issue by cj-cuccaro** [DroneDB/DroneDB#152]
Some directories on a cloud drive don't load. 

https://user-images.githubusercontent.com/44933037/103102011-24610780-45e8-11eb-8bc2-cfbd85680769.mp4

**Comment by pierotofy** [comment]
Hey @cj-cuccaro, thanks for the report!

Does this happen with every folder in OneDrive?

**Comment by cj-cuccaro** [comment]
Looks like it is just the one for me...

Let me know if have other questions.
https://user-images.githubusercontent.com/44933037/103140257-79695000-46b2-11eb-8e20-33365961f70a.mp4



https://user-images.githubusercontent.com/44933037/103140276-a584d100-46b2-11eb-87d9-d37985e0c0e5.mp4
