### ISSUE TITLE
Add "fast init" mechanism

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/DroneDB#167]
`ddb init` spends a lot of time building the dbase.sqlite table structure.

We could simply generate an empty database at build time and static-copy the empty database from the app data directory with `ddb init`.

**Comment by pierotofy** [comment]
In short, right after compilation, run a `git init --from-scratch` to generate a `.ddb/dbase.sqlite` and copy it in the build directory, which generates an empty database.

When running `ddb init`, the software checks whether a dbase.sqlite is available in the data directory and copy it instead of regenerating it from scratch.

**Comment by HeDo88TH** [comment]
Closed by #180
