### ISSUE TITLE
Don't compute hashes with ddb share by default

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/DroneDB#191]
For the sake of increasing speed, we shouldn't compute hashes when using `ddb share` since it slows down upload time.

We can add a flag to do a "integrity verified upload" that keeps the current logic. Most uploads succeed just fine.

**Comment by HeDo88TH** [comment]
Is this a registry enhancement?

**Comment by pierotofy** [comment]
Nop, just the ddb client.
