### ISSUE TITLE
Bug: Thumbnailing issue with + character in filename

### ISSUE THREAD

**Issue by Saijin-Naib** [DroneDB/DroneDB#194]
Seems like image names containing certain non-standard characters (+ especially) break thumbnailing of the images in DroneDB.
https://community.opendronemap.org/t/webodm-lightning-failure-due-to-lack-of-ram/6970/13?u=saijin_naib

**Comment by pierotofy** [comment]
Yep, can confirm. Thanks for the report @Saijin-Naib !

**Comment by Saijin-Naib** [comment]
> Yep, can confirm. Thanks for the report @Saijin-Naib !

Any time, Piero.

I have not confirmed yet, but I have a strong suspicion the character handling for filenames might be biting the user the same way with GCP Editor Pro. Once I get his confirmation, I'll file a bug there as well, but just a heads up for now.
