### ISSUE TITLE
Ensure tables exist before querying them

### ISSUE THREAD

**Issue by HeDo88TH** [DroneDB/DroneDB#202]
It happens that on old databases the `attributes` table does not exist. We should test for existence before querying sqlite tables. At least before we have some kind of DB versioning system.

**Comment by HeDo88TH** [comment]
This is partially fixed in https://github.com/DroneDB/DroneDB/pull/200/commits/f537a392923599e7fb29df21f9b64a4484a5ff95. I keep this issue open just for reference if we will be back on this.

**Comment by pierotofy** [comment]
Schema consistency should be now enforced at every open.
