### ISSUE TITLE
EPT command giving strange proj errors

### ISSUE THREAD

**Issue by HeDo88TH** [DroneDB/DroneDB#242]
Test dataset: https://www.limon.eu/UserFiles/sample_data/Palac_Moszna.zip

Result:

```
C:\Users\IT 2\Downloads\Palac_Moszna>ddb ept out Palac_Moszna.laz
proj_create_from_database: datum not found
proj_create_from_database: ellipsoid not found
proj_create_from_database: prime meridian not found
proj_create_from_database: datum not found
proj_create_from_database: ellipsoid not found
proj_create_from_database: prime meridian not found
out\tmp cannot be removed
```

The files are correctly generated but the temp folder (out\tmp) was not removed.

Maybe there is something wrong with the first dataset, because this one works flawlessly: https://www.limon.eu/UserFiles/sample_data/G_Sw_Anny.zip

**Comment by pierotofy** [comment]
This worked fine on my Linux box.

**Comment by pierotofy** [comment]
Closing as I think this was a problem related to proj's installation.
