### ISSUE TITLE
File Size Limit Exceeded?

### ISSUE THREAD

**Issue by Saijin-Naib** [DroneDB/DroneDB#281]
```
{"error":"MinIO API responded with message=Connection error: Stream was too long.. Status code=0, response=Stream was too 
long., content="}
```
https://testhub.dronedb.app/orgs/saijinnaib/ds/ankit_bhatla/download/ankit_bhatla_2021-09-12_Original_05m.zip

```
{"error":"MinIO API responded with message=Connection error: Stream was too long.. Status code=0, response=Stream was too long., content="}
```
https://testhub.dronedb.app/orgs/saijinnaib/ds/ankit_bhatla/download/ankit_bhatla_2021-09-12_preprocessed_05m.zip

----

Interestingly enough, if I try to select both of these too large files it will zip and ship an empty copy of the first item only, but it will not error out the same way.

**Comment by pierotofy** [comment]
Uh! Nice find. I wonder why that's happening. We'll fix it.

**Comment by pierotofy** [comment]
This should be fixed.
