### ISSUE TITLE
Question: Total available datasets?

### ISSUE THREAD

**Issue by farhadinima75** [DroneDB/DroneDB#284]
Hi there.
first of all, I wana say thanks for a great app.

Is there a way to find out about available datasets? 
Thanks in advance.

**Comment by HeDo88TH** [comment]
> Hi there. first of all, I wana say thanks for a great app.

Thanks! 

> Is there a way to find out about available datasets? Thanks in advance.

You can see your datasets but there is currently no way to discover public datasets. Nevertheless you can open them if you get the link.

**Comment by pierotofy** [comment]
This could probably be a feature to add (a catalog of public datasets?)

**Comment by HeDo88TH** [comment]
This would be pretty cool. We could follow what YouTube does: public, unlisted, private.

**Comment by farhadinima75** [comment]
@HeDo88TH @pierotofy thanks for the quick response. 
yes, it could be a great feature. is it clear how long does it takes to be an available feature?

**Comment by farhadinima75** [comment]
Thanks @pierotofy for your propose but I'm not that expert to contribute in such project. I'll wait for new releases.
Closing issue.
