### ISSUE TITLE
Uploaded point clouds don't display in viewer if they lack GPS data

### ISSUE THREAD

**Issue by TimeScience** [DroneDB/DroneDB#290]
Hi,

I was testing the ability of dronedb to visualise uploaded point clouds. The first point cloud I uploaded had no GPS and when I switch to the 3D view, I get a _"No point cloud selected"_ error. I figured this might be related to the lack of GPS but then I loaded a correctly georeferenced image and for that one, the potree interface loads with no error, but no data is shown. 
After a ~5min delay, the second dataset (with GPS) loaded fine, so I presume that was a delay in processing that isn't noted in the UI, but the non-gps'd point cloud still throws the _"No point cloud selected"_ error, so this is more likely an issue with the point cloud not having GPS.

Example dataset that doesn't work is [here](https://cloudstor.aarnet.edu.au/plus/s/H3NSloWsalknZzS)

Point cloud with no georeferencing - UI says 'no point cloud selected' error
![image](https://user-images.githubusercontent.com/3067588/137063523-a3d8b2c1-ba9a-4fd5-9c42-936495374b5d.png)

**Comment by pierotofy** [comment]
Thanks @TimeScience ! We currently only support .las/.laz. We need to add support for ply. As a temporary workaround, you can convert the PLY to LAZ via PDAL.
