### ISSUE TITLE
Consider keeping sensor width database in JSON format

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/DroneDB#3]
It might make it easier to edit, add new sensors.

**Comment by natowi** [comment]
A comprehensive sensor database can be found here https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/sensorDB/cameraSensors.db (MPL2 license)

**Comment by pierotofy** [comment]
Very nice! We've been using the one from https://github.com/mapillary/OpenSfM/blob/master/opensfm/data/sensor_data.json but Alice Vision's seems comprehensive too. Perhaps we could use both!
