### ISSUE TITLE
Ability to display textured models 

### ISSUE THREAD

**Issue by HeDo88TH** [DroneDB/DroneDB#306]
From user feedback. We should add support for textured models.

Starting points: 
- https://threejs.org/docs/index.html?q=3d#manual/en/introduction/Loading-3D-models 
- https://3dviewer.net/
- https://github.com/mrdoob/three.js/tree/dev/examples/jsm/loaders

My only concern is the file size. I think it should have some kind of tiling system like potree.

**Comment by pierotofy** [comment]
We need to bring http://vcg.isti.cnr.it/nexus/ and generate nexus files (just like we build EPT/COGs)

**Comment by pierotofy** [comment]
https://github.com/DroneDB/libnexus
