### ISSUE TITLE
Remove DSM service

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/DroneDB#311]
It's just not reliable; either we find a way to incorporate an offline coarse DEM, or disable the ability to geoproject files that lack relative altitude.

**Comment by HeDo88TH** [comment]
Could this be useful? https://gisgeography.com/free-global-dem-data-sources/

**Comment by pierotofy** [comment]
Maybe; at some point we might need to setup an elevation server that we can control.

**Comment by pierotofy** [comment]
No easy way to do this; setting up an accurate elevation server is no easy feat.
