### ISSUE TITLE
Video uploads stuck at 100%

### ISSUE THREAD

**Issue by JustinBack** [DroneDB/DroneDB#320]
Are large-ish file upload supported? (Around 3 Gigs)

Whenever I upload a video that's roughly 3 gigabytes large, whether its via the hub or the cli it gets stuck at 100% forever. No logs, just stuck at 100%.

A video thats 2,99 GB big gets uploaded flawlessly.

<img width="137" alt="Bildschirmfoto 2022-05-29 um 16 40 10" src="https://user-images.githubusercontent.com/40178814/170875252-741e46dc-38eb-497d-acbf-bfb2133e00b6.png">

<img width="220" alt="Bildschirmfoto 2022-05-29 um 16 41 51" src="https://user-images.githubusercontent.com/40178814/170875258-b1574579-6e39-4ec5-8aa7-96e4bd4d8684.png">

I use nginx as a reverse proxy with the timeout increased to 300 seconds as well as modifying the keep-alive string (noticed that removing the keep-alive header nothing changes). Without these nginx changes the request gets a 504 gateway timeout.

**Comment by HeDo88TH** [comment]
Please write an e-mail to [support@dronedb.app](mailto:support@dronedb.app) . This place is for issues related to the DroneDB library only. Thanks.
