### ISSUE TITLE
Feature Request: American Imperial Units

### ISSUE THREAD

**Issue by Karageek** [DroneDB/DroneDB#323]
Ability to toggle or change default units to American Imperial units, Feet, Inches, etc.  This will be more helpful for those that I often share data with are not very proficient with Metric.

**Comment by pierotofy** [comment]
This should be fixed with https://github.com/DroneDB/Hub/commit/e9155c07e5e3f956f1cf4731f39483247f6b9351

<img width="602" alt="image" src="https://user-images.githubusercontent.com/1951843/187025516-81386d0c-8060-4e49-8f33-92cb2e3e9b7c.png">

🎉
