### ISSUE TITLE
Upgrade vendor/googletest to be compatible with modern Python

### ISSUE THREAD

**Issue by cclauss** [DroneDB/DroneDB#335]
`vendor/googletest` is an out-of-date version that is compatible with Python 2 but not with Python 3.  Given that Python 2 died more than 1,000 days ago on 1/1/2020, it should be considered insecure and may it not be installed on several modern operating systems.  https://github.com/google/googletest

**Comment by pierotofy** [comment]
Thanks for the report. Would you be interested in opening a PR @cclauss ?

**Comment by pierotofy** [comment]
Closing, feel free to open a PR with the aforementioned improvement. 🙏
