### ISSUE TITLE
Link to the system installed dependencies

### ISSUE THREAD

**Issue by chenrui333** [DroneDB/DroneDB#350]
Right now, it always include [the vendor files](https://github.com/DroneDB/DroneDB/blob/master/CMakeLists.txt#L177-L179), but on the homebrew side, it does cause [the linkage issues](https://github.com/Homebrew/homebrew-core/pull/116073#issuecomment-1328146600). Can you conditionally link the dependencies into the system installed ones? Thanks!

**Comment by chenrui333** [comment]
cc @pierotofy

**Comment by pierotofy** [comment]
We unfortunately cannot use the system exiv2, it's dated in several distro, I think it might just be a matter of not installing the library/headers into the homebrew environment (we link statically so no problem there). I'll have a PR with a tentative fix soon.

**Comment by pierotofy** [comment]
Released https://github.com/DroneDB/DroneDB/releases/tag/v1.0.12 which includes the proposed fix.

ddb no longer installs any of the libexiv2 headers/libraries so should fix the problem that was being experienced in homebrew.

**Comment by chenrui333** [comment]
Thanks @pierotofy, gonna give 1.0.12 a shot!
