### ISSUE TITLE
Corrupt hosted texture/image downloads

### ISSUE THREAD

**Issue by Lucent** [DroneDB/DroneDB#358]
As of yesterday I'm seeing failures to fetch both images and textures for the 3D model I've uploaded. Console shows a lot of content length mismatch errors.

https://hub.dronedb.app/orgs/lucent/ds/bluff/download/Photos/DJI_0098.JPG?inline=1
https://hub.dronedb.app/r/lucent/bluff/view/M0QgTW9kZWwvb2RtX3RleHR1cmVkX21vZGVsX2dlby5vYmo=/model

The second link, a 3D model, should appear with fairly high resolution texture, not the blocky, blurry model that initially appears, suggesting texture files aren't downloading. People around the world I've sent this to have reproduced the problem.

**Comment by pierotofy** [comment]
I know this is an old issue, but downloads *should* be working now; feel free to re-open this if the issue is still present 🙏
