### ISSUE TITLE
DroneDB Desktop

### ISSUE THREAD

**Issue by wyatt300** [DroneDB/DroneDB#379]
Hello, I am having an issue with the desktop application. When I open the application, it is frozen trying to load but nothing ever happens. I have tried deleting and reinstalling, no changes
<img width="1280" alt="Screenshot 2023-08-23 075841" src="https://github.com/DroneDB/DroneDB/assets/138246934/a2b590c8-94bb-4e66-b17a-2088e21b1059">

**Comment by pierotofy** [comment]
Sorry for the late reply; is the issue still happening? Was it working at any point in time (or it never worked?)

**Comment by Saijin-Naib** [comment]
I've only seen this locally with a network path or drive mounted in Windows that isn't reachable, like if your NAS goes offline, or your network drives from work are disconnected because your VPN isn't active.

Do you happen to have any network drives mounted, or all local drives only?

**Comment by wyatt300** [comment]
Local only

**Comment by pierotofy** [comment]
Try to open:

`C:\Users\<youruser>\AppData\Local\Programs\`

And delete the `DroneDB` folder. Then re-install the program.

Does it work then?

**Comment by wyatt300** [comment]
It is still not working

**Comment by pierotofy** [comment]
Really strange; this is a difficult one to troubleshoot because we don't know for sure what caused it to get into that state.

If you'd like a refund for the license, get in touch via https://dronedb.app/contact/ 🙏

**Comment by HeDo88TH** [comment]
Please write an e-mail to [support@dronedb.app](mailto:support@dronedb.app) . This place is for issues related to the DroneDB library only. Thanks.
