### ISSUE TITLE
Update the documentation to explain `EXTERNAL_URL`

### ISSUE THREAD

**Issue by GeoSpark** [DroneDB/DroneDB#395]
As asked (and now answered) [here](https://github.com/DroneDB/DroneDB/discussions/386) Those of us running DroneDB in Docker behind a reverse proxy have issues with the `list` endpoint being requested as HTTP instead of HTTPS. While `ExternalUrlOverride` _is_ mentioned in the docs, it's not mentioned that it is associated with the env var `EXTERNAL_URL`. Neither is it mentioned in the FAQ.
Could the docs be updated to give explicit guidance for reverse proxy users on the use of `EXTERNAL_URL` and associate it with `ExternalUrlOverride`

**Comment by HeDo88TH** [comment]
Are you talking about Registry or Server?
