### ISSUE TITLE
Cant access DroneDB Cloud Platform

### ISSUE THREAD

**Issue by Mastercol3n** [DroneDB/DroneDB#404]
For some reason since the announcement of the tier changes, I can no longer access the cloud platfrom of the Hub to upload or view any of my uploaded files. It just sits there spinning the circle never loading. I have the legacy professional tier subscription and all payments are being processed. not sure what is happening here. 

![screenshot](https://github.com/user-attachments/assets/a39a9134-e6be-4900-91a2-31bb4e7b0096)

**Comment by HeDo88TH** [comment]
Please write an e-mail to support@dronedb.app . This place is for issues related to the DroneDB library only. Thanks.
