### ISSUE TITLE
allow named projects / pilots

### ISSUE THREAD

**Issue by adamsteer** [DroneDB/DroneDB#53]
it would help from my POV to be able to filter flights by pilot or by 'project/survey' name. What are your thoughts? it would mean two freeform text fields in the DB table.

In my mind having metadata fields for those details is safer than relying on path names..

**Comment by pierotofy** [comment]
Indeed; this is an interesting part of the design that needs to be addressed. One thing is quite certain, is that there are no established standards for what type of metadata (project name, pilot, hardware used, etc.) people want to use. 

We can choose some sensible fields for our users, but, I fear this will lead to an inflexible system.

My current approach (to be implemented) is for users to have the ability to define schemas for any set of entries in the DB.

Say you index a folder `images` and you want to mark that folder to have a `Pilot name` field, you should be able to do so by defining a schema for the `images` entry:

`ddb schema add pilot images/` (or something similar)

Where `pilot` refers to a schema definition file (also to be defined) that contain rules for fields, validation rules, ability to reference other metadata (sort of a simplified join).

```json
{
     "schema": {
           "pilot": { "type": "String", "required": true, "dataSource": "$ref:pilots" },
           "flightDate": { "type": "Date" }
     }
}```

Then we could provide sensible default "recommended schemas" for common use cases, while allowing users to define their own rules/schemas.

A bit ambitious perhaps, but should allow for some degree of flexibility; not flexible like a custom built database, but flexible enough to cover 98% of use cases.

**Comment by adamsteer** [comment]
perfect! I'm not sure I can help code that, but I can test it out ;)

**Comment by pierotofy** [comment]
We appreciate all the help we can get in any area. :+1:  It might be a few months before we can begin work on this though. I'll update this thread once we do.
