### ISSUE TITLE
Proposal to create testing releases

### ISSUE THREAD

**Issue by HeDo88TH** [DroneDB/DroneDB#79]
It would be nice to have both the generation of stable releases and testing releases. I noticed that I had to build from sources to get the latest features not present in the latest stable release.

**Comment by pierotofy** [comment]
I'm personally a fan of the rolling-release model https://en.wikipedia.org/wiki/Rolling_release where you just assume that the master branch is the latest working version (especially this early in the development).

But if there are pros to having stable/testing releases, we can try that.
