### ISSUE TITLE
Add ddb list command to list files in the index

### ISSUE THREAD

**Issue by HeDo88TH** [DroneDB/DroneDB#81]
Add `ddb list` (alias `ddb ls`) to list the contents of the index. It works like the `ls` command of the file system

**Comment by pierotofy** [comment]
Can set it up either like:

`ls -R dir/`

```
.:
DJI_0034.JPG DJI_0035.JPG

./test:
test.txt
```

or like the output of `tree dir/`

```
.
├── DJI_0034.JPG
├── DJI_0035.JPG
└── test
    └── test.txt
```
