### ISSUE TITLE
Add ddb status command to show the diff between the index and the fs

### ISSUE THREAD

**Issue by HeDo88TH** [DroneDB/DroneDB#82]
This command shows the difference between the index and the filesystem: added files, removed files and modified files

**Comment by HeDo88TH** [comment]
A couple of implementation details:

- Is it going to be folder-sensitive? I.E. have target folder, recursive and maxdepth parameters to narrow down the results?
- More down the line

**Comment by pierotofy** [comment]
> Is it going to be folder-sensitive? 

Yes.

> I.E. have target folder, recursive and maxdepth parameters to narrow down the results?

No, we can probably make it work similar to `git status` (diff the entire tree).
