### ISSUE TITLE
Implement easy rollback

### ISSUE THREAD

**Issue by HeDo88TH** [DroneDB/DroneDB#93]
It would be a good idea to implement some sort of "fast rollback". The user is able to rollback the last action performed on the index (add / remove) with a simple command.
It could work by making a backup copy of the sqlite database before each command and swap it when asked for restore.

**Comment by pierotofy** [comment]
Yes; you could add versioning at that point too. Not a priority though.

**Comment by pierotofy** [comment]
Not going to be implemented, unless requested by users.
