### ISSUE TITLE
Add support for setting password(s)

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/DroneDB#96]
- [ ] Add a `password` table when creating a DDB database (two fields, `salt` and `sha256`, or other as best practices recommend)
- [x] Rename current `ddb set` to `ddb exif set` (this might require some tweaking of the cmd line arg parsing logic).
- [ ] Allow the user to invoke (on a valid DroneDB database): `ddb set password <password> [-d ddb dir (optional)] [--append,-a (optional)] [---clear,-c]` (`-a` appends to the list of valid passwords, `-c` clears all passwords).
- [ ] Add API bindings for .NET/NodeJS for the same functions above
- [ ] Add API bindings for checking if the database has one or more password set 
- [ ] Add API bindings for verifying a correct, user-supplied password

**Comment by HeDo88TH** [comment]
Should we also password-protect the entire sqlite database?
Is this password system only a "metadata" feature to provide an authorized list of users from reading the database?
What happens if the sqlite is leaked and someone without password gets access to it?

**Comment by pierotofy** [comment]
> Should we also password-protect the entire sqlite database?

No.

> Is this password system only a "metadata" feature to authorize a specific list of users to read the database?

Yes.

> What happens if the sqlite is leaked and someone without password gets access to it?

The world as we know it ends.

We won't care about that for the time being. Maybe in a future release...

**Comment by HeDo88TH** [comment]
> The world as we know it ends.

:trollface:

**Comment by HeDo88TH** [comment]
Implementation proposal, fast and dry:

Append new password
```
ddb password -d "C:\img" --append "testpassword"
ddb password -d "C:\img" -a "testpassword"
```

Verifies if a password is found
```
ddb password -d "C:\img" --verify "testpassword"
ddb password -d "C:\img" -v "testpassword"
```

Removes a password
```
ddb password -d "C:\img" --remove "testpassword"
ddb password -d "C:\img" -r "testpassword"
```

Clears all the saved passwords
```
ddb password -d "C:\img" --clear
ddb password -d "C:\img" -c
```

Internal implementation: add new `passwords` table with columns: `salt` and `hash`.
`salt` is randomly generated and `hash` is `sha256(salt + hash)`

Add new `PasswordManager` class that encapsulates all the code related to password `add`/`remove`/`verify`

**Comment by pierotofy** [comment]
This one:

```
ddb password -d "C:\img" --remove "testpassword"
ddb password -d "C:\img" -r "testpassword"
```

Is probably not needed (clear all will serve the purpose fine for now).

To clarify, `ddb password --verify` with an empty parameter (default "") should return `positive` (`true`) if the archive has no passwords. In fact if the archive has no password(s), verify should always return true.

OK with the rest.

**Comment by HeDo88TH** [comment]
I've improved the command structure in https://github.com/DroneDB/DroneDB/pull/121/commits/413e988322463a4fdd4d877968759478ecd5dd79

We can use the command like this:

Append new password

```
ddb password append "testpassword" -w "C:\img"
ddb password a "testpassword" -w "C:\img"
```

Verifies if a password is found

```
ddb password verify "testpassword" -w "C:\img"
ddb password v "testpassword" -w "C:\img"
```

Clears all the saved passwords

```
ddb password clear -w "C:\img"
ddb password c -w "C:\img"
```
